
console.log("DEBUG: viewer_pro.js started");

try {
    var html = [];
    html.push('<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><title>QX Data</title><style>');
    html.push('body{background:#000;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;padding:16px;margin:0}');
    html.push('h1{font-size:24px;margin:0 0 16px 4px;font-weight:700}');
    html.push('h3{font-size:13px;color:#888;margin:20px 0 6px 12px;text-transform:uppercase;letter-spacing:0.5px}');
    html.push('.card{background:#1c1c1e;border-radius:12px;overflow:hidden;margin-bottom:8px}');
    html.push('.row{padding:12px 16px;border-bottom:1px solid #2c2c2e;display:flex;align-items:center;justify-content:space-between}');
    html.push('.row:last-child{border-bottom:none}');
    html.push('.val{font-family:Menlo,Monaco,Consolas,monospace;font-size:12px;color:#32d74b;width:100%;overflow-x:auto;white-space:pre-wrap;word-break:break-all;background:transparent;border:none;resize:none;outline:none}');
    html.push('.empty{color:#555;font-style:italic;font-size:13px}');
    html.push('.btn{display:inline-block;padding:6px 12px;border-radius:6px;font-size:13px;font-weight:600;text-decoration:none;margin-left:8px;flex-shrink:0}');
    html.push('.btn-del{background:rgba(255,69,58,0.15);color:#ff453a}');
    html.push('.btn-main{background:#0a84ff;color:#fff;display:block;text-align:center;padding:14px;border-radius:12px;margin-top:24px;font-size:16px;font-weight:600;text-decoration:none}');
    html.push('</style></head><body>');
    html.push('<h1>QX Data</h1>');

    var base = "http://qxdata.liangjima.com";
    if (typeof $request !== "undefined" && $request.url) {
        var parts = $request.url.split("/");
        if (parts.length >= 3) {
            base = parts[0] + "//" + parts[2];
            if ($request.url.indexOf("/qx-data") !== -1) {
                base += "/qx-data";
            }
        }
    }

    if (typeof $prefs === "undefined") {
        throw new Error("$prefs is undefined");
    }

    var keys = ["nodeloc_auth_cookie", "nodeloc_auth_auth", "nodeseek_auth_cookie", "nodeseek_auth_auth"];
    var labels = ["NodeLoc Cookie", "NodeLoc Auth", "NodeSeek Cookie", "NodeSeek Auth"];

    html.push('<h3>Cookies & Auth</h3>');
    html.push('<div class="card">');
    for (var i = 0; i < keys.length; i++) {
        var k = keys[i];
        var v = $prefs.valueForKey(k);
        html.push('<div class="row">');
        html.push('<div style="width:100%">');
        html.push('<div style="font-size:15px;margin-bottom:4px;color:#fff">' + labels[i] + '</div>');
        if (v) {
            var cleanV = String(v).replace(/"/g, "&quot;");
            html.push('<textarea class="val" rows="3" readonly onclick="this.select()">' + cleanV + '</textarea>');
            html.push('</div>');
            html.push('<a href="' + base + '/delete?key=' + k + '" class="btn btn-del">Delete</a>');
        } else {
            html.push('<div class="empty">No Data</div>');
            html.push('</div>'); 
        }
        html.push('</div>'); 
    }
    html.push('</div>'); 

    var bv = $prefs.valueForKey("RESP_barventory");
    html.push('<h3>Barventory Response</h3>');
    html.push('<div class="card">');
    html.push('<div class="row">');
    if (bv) {
        var cleanBv = String(bv).replace(/"/g, "&quot;");
        html.push('<div style="width:100%"><textarea class="val" rows="6" readonly onclick="this.select()">' + cleanBv + '</textarea></div>');
        html.push('<a href="' + base + '/delete?key=RESP_barventory" class="btn btn-del">Clear</a>');
    } else {
        html.push('<div class="empty" style="padding:4px 0">No captured response</div>');
    }
    html.push('</div></div>');

    html.push('<a href="' + base + '/clear" class="btn-main">Clear All Data</a>');
    
    html.push('<div style="text-align:center;color:#444;margin-top:20px;font-size:12px">Generated by QX Script</div>');
    html.push('</body></html>');

    $done({
        status: "HTTP/1.1 200 OK",
        headers: {"Content-Type": "text/html;charset=UTF-8"},
        body: html.join("")
    });

} catch (e) {
    console.log("DEBUG: Error " + e);
    $done({
        status: "HTTP/1.1 200 OK",
        headers: {"Content-Type": "text/html;charset=UTF-8"},
        body: "<h1>JS Error</h1><pre>" + e + "</pre>"
    });
}
